version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: wallet
      MONGO_INITDB_ROOT_PASSWORD: wallet

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    ports: ["9000:9000"]
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: ./gateway
    ports: ["8080:8080"]
    depends_on: [auth-service]

  user-service:
    build: ./user-service
    ports: ["8081:8080"]
    depends_on:
      postgres:
        condition: service_healthy

  wallet-service:
    build: ./wallet-service
    ports: ["8082:8080"]
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  merchant-service:
    build: ./merchant-service
    ports: ["8083:8080"]
    depends_on: [mongodb]

  payment-gateway-service:
    build: ./payment-gateway-service
    ports: ["8084:8080"]