server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates: [Path=/api/user/**]
        - id: wallet-service
          uri: http://wallet-service:8080
          predicates: [Path=/api/wallet/**]
        - id: merchant-service
          uri: http://merchant-service:8080
          predicates: [Path=/api/merchant/**]
        - id: payment-gateway-service
          uri: http://payment-gateway-service:8080
          predicates: [Path=/api/pay/**]
        - id: notification-service
          uri: http://notification-service:8080
          predicates: [Path=/notifications/**]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:9000
  redis:
    host: redis
    port: 6379
jwt:
  secret: ENC(${JWT_SECRET})
  expirationMs: 3600000