server:
  port: 8080
spring:
  application:
    name: payment-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:9000
jwt:
  secret: ENC(${JWT_SECRET})
  expirationMs: 3600000