server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/wallet
    username: wallet
    password: wallet
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-service:9000